tdameros/42-transcendence

- tournament/src/api/tests.py
- tournament/src/api/urls.py
- tournament/src/tournament/settings.py
I made you a basic test, but I can't launch it myself ( I can't find your .env ???) 
This is the strict basics, so you understand how it's work.
To test this, you can type `python3 manage.py test` and Django will launch every function starting with 'test_'
no need to do ` .. runserver`
If you want to add breakpoints in your test, I've put a useful message in discord ! ..
> Tournament creation unit test proposal

- .github/DOClient.py
- .github/SSHClient.py
- .github/restore_deployment.py
- .github/update_deployment.py
- .github/workflows/restore_deployment.yaml
- .github/workflows/update_deployment.yaml
Adding 2 new functionalities to our GitHub actions for automatically deploying our changes to a DigitalOcean server (42.shiftcode.fr).
- Update Deployment: Upon each push to the main branch, a script connects via SSH to the server, performs a 'make down', 'git pull', and 'make up' to restart with the latest updates.
- Restore Deployment: In the event of major changes or bugs, a manual action dispatch can be triggered to restore the server to an empty snapshot and redeploy the project from scratch. This functionality will be used when the Docker architecture changes (e.g., rebuilding images, restoring volumes, changing networks...).
> Autodeploy

- doc/Documentation.md
- user_management/doc/User_management.md
- user_management/src/user/tests.py
- user_management/src/user/urls.py
renamed refresh-jwt into refresh-access-jwt
> renamed refresh-jwt into refresh-access-jwt

- doc/Documentation.md
- user_management/doc/User_management.md
- user_management/src/user/tests.py
- user_management/src/user/urls.py
- user_management/src/user/views.py
- user_management/src/user_management/settings.py
will return a user object when successful
Might be extended to return more information in the future, if needed
<details>
<summary><code>GET</code><code><b>/user/{user_id}/</b></code></summary>
{user_id}
> 
> NB : user_id must be an integer
> 
> | http code | content-type       | response                                             |
> |-----------|--------------------|------------------------------------------------------|
> | `200`     | `application/json` | `{"username": "..."}`                                |
> | `404`     | `application/json` | `{"errors": ["User not found"]}`                     |
> | `400`     | `application/json` | `{'errors': ['User id must be an integer']}`         |
> | `500`     | `application/json` | `{"errors": ['An unexpected error occurred : ...']}` |
>
> added the /user/{user_id} route

- doc/Documentation.md
- user_management/doc/User_management.md
- user_management/src/user/tests.py
- user_management/src/user/urls.py
- user_management/src/user/views.py
- user_management/src/user_management/settings.py
will return a list of usernames that contains the searched username
<details>
<summary><code>POST</code><code><b>/search-username/</b></code></summary>
> ``` javascript
>   
> {
>    "username": "Aurel"
> }
> ```
> 
> NB : An empty username will return an error "Username not found"
> | http code | content-type       | response                                             |
> |-----------|--------------------|------------------------------------------------------|
> | `200`     | `application/json` | `{"usernames": ["Aurel", "Aurel2", "Aurel3"]}`       |
> | `400`     | `application/json` | `{"errors": ["AAA"]}`                                |
> | `500`     | `application/json` | `{"errors": ['An unexpected error occurred : ...']}` |
> 
> errors can be :
> - Invalid JSON format in the …
> UM search-username

- tournament/src/api/tests/test_tournament.py
- tournament/src/api/views/tournament_views.py
- tournament/src/tournament/settings.py
In the `DELETE /tournament` endpoint:
- player unregistered from the tournament in which he is participating (only tournaments in the registration phase)
> player unregistered from the tournament in which he is participating

- tournament/doc/tournament-api-documentation.md
- tournament/src/api/tests/test_tournament_players.py
- tournament/src/api/urls.py
- tournament/src/api/views/tournament_players_views.py
Replaces all user nicknames with `Anonymous`.
> Add `POST /tournament/player/anonymize`

- .github/workflows/front.yaml
- front/app/.eslintrc.json
- front/app/babel.config.cjs
- front/app/package.json
- front/app/src/js/Cookies.js
- front/app/src/js/Router.js
- front/app/src/js/Theme.js
- front/app/src/js/components/Component.js
- front/app/src/js/components/Home.js
- front/app/src/js/components/Multiplayer.js
- front/app/src/js/components/Navbar.js
- front/app/src/js/components/ResetPassword.js
- front/app/src/js/components/Signin.js
- front/app/src/js/components/Signup.js
- front/app/src/js/components/Singleplayer.js
- front/app/src/js/components/ThemeButton.js
- front/app/src/js/components/Tournaments.js
- front/app/src/js/main.js
- front/app/src/js/utils/BootstrapUtils.js
- front/app/src/js/utils/InputValidator.js
- front/app/tests/InputValidator.test.js
- front/app/vite.config.js
- Added a JavaScript linter based on the Google config.
- Refactored files to comply with the linter.
- Added unit tests.
- Implemented a GitHub Actions workflow.
> Create front workflow

- tournament/src/api/views/tournament_views.py
Add nb-players in `GET /tournament`
> Add nb-players in `GET /tournament`

- doc/Documentation.md
- user_management/doc/User_management.md
- user_management/src/user/tests.py
- user_management/src/user/urls.py
- user_management/src/user/views/sign_up.py
- user_management/src/user/views/update_infos.py
- user_management/src/user_management/utils.py
User can now edit it's information.
Will later be used to upload avatar
> Um user update infos

- tournament/src/api/tests/test_manage_tournament.py
- tournament/src/api/views/manage_tournament_views.py
it is no longer possible to delete a tournament in progress
> fix `DELETE /tournament/{id}`

- user_stats/doc/user-stats-documentation.md
- user_stats/src/api/tests/test_user_history.py
- user_stats/src/api/views/user_history.py
Add total_pages field to `/statistics/user/{id}/history/` endpoint
> User stats pages

- doc/Documentation.md
- front/doc/component.md
- front/doc/router.md
- Update front documentation with new features
> update front documentation

- front/app/src/js/components/index.js
- front/app/src/js/components/pages/NotFound.js
- front/app/src/js/components/pages/index.js
- front/app/src/js/components/utilities/Error.js
- front/app/src/js/main.js
- front/app/src/js/utils/ErrorPage.js
- Add default page when route is not found
> implement page NotFound

- common/src/settings.py
- user_management/src/user/tests.py
- user_management/src/user/views/sign_up.py
Add a POST on `user-stats` to create user when signing up
> Signup user stats

- .github/workflows/pong-server.yaml
- pong_server/.gitignore
- pong_server/dev_deprecated_redirection_server.sh
- pong_server/dev_game_creator.sh
- pong_server/docker/Dockerfile
- pong_server/docker/docker-compose.yaml
- pong_server/docker/gunicorn/gunicorn.conf.py
- pong_server/docker/run.sh
- pong_server/linter.sh
- pong_server/src/game_creator/api/GameCreator.py
- pong_server/src/game_creator/api/tests.py
- pong_server/src/game_creator/api/urls.py
- pong_server/src/game_creator/api/views.py
- pong_server/src/game_server/Game.py
- pong_server/src/game_server/Scene/Ball.py
- pong_server/src/game_server/Scene/Match.py
- pong_server/src/game_server/Scene/Player/Paddle.py
- pong_server/src/game_server/Scene/Player/Player.py
- pong_server/src/game_server/Scene/Player/_Board.py
- pong_server/src/game_server/Scene/PlayerFinder/PlayerFinder.py
- pong_server/src/game_server/Scene/PlayerFinder/PlayerLocation.py
- pong_server/src/game_server/Scene/Scene.py
- pong_server/src/game_server/Scene/bounding_boxes.py
- pong_server/src/game_server/main.py
- pong_server/src/game_server/settings.py
- pong_server/src/game_server/update_player_movement_and_position.py
- pong_server/src/redirection_server_deprecated/Game.py
- pong_server/src/redirection_server_deprecated/main.py
- pong_server/src/shared_code/setup_logging.py
Changed pong-server file architecture to properly separate the different programs
> pong-server file architecture refactoring

- front/src/threejs/Documentation.md
- front/src/threejs/Engine/sockets/_GameSocketIO.js
- front/src/threejs/Scene/Ball.js
- front/src/threejs/Scene/Match.js
- front/src/threejs/Scene/Scene.js
- pong_server/dev_deprecated_redirection_server.sh
- pong_server/dev_game_creator.sh
- pong_server/src/game_server/Game.py
- pong_server/src/game_server/Scene/Ball.py
- pong_server/src/game_server/Scene/Match.py
- pong_server/src/game_server/Scene/Player/Paddle.py
- pong_server/src/game_server/Scene/Player/Player.py
- pong_server/src/game_server/Scene/Player/_Board.py
- pong_server/src/game_server/Scene/Scene.py
- pong_server/src/game_server/main.py
- pong_server/src/game_server/settings.py
- pong_server/src/game_server/update_player_movement_and_position.py
- pong_server/src/shared_code/emit.py
When a player scores a point the ball now waits for a few seconds before moving again.
The score is now kept track of.
Also fixed the game server not cleaning up correctly on shutdown
> Pong game points

- front/docker/docker-compose.yaml
- pong_server/docker/docker-compose.yaml
- pong_server/src/game_creator/game_creator/urls.py
- pong_server/src/game_creator/game_creator/views.py
- tournament/docker/docker-compose.yaml
- tournament/src/tournament/urls.py
- tournament/src/tournament/views.py
- user_management/docker/docker-compose.yaml
- user_management/src/user_management/urls.py
- user_management/src/user_management/views.py
- user_stats/docker/docker-compose.yaml
- user_stats/src/user_stats/urls.py
- user_stats/src/user_stats/views.py
Add healthcheck to Docker Compose to resolve migration problems when the database is not yet available, and to prevent nginx errors when Gunicorn servers are not yet available
https://laurent-bel.medium.com/waiting-for-postgresql-to-start-in-docker-compose-c72271b3c74a
> Add docker health check

- pong_server/docker/docker-compose.yaml
- tournament/docker/docker-compose.yaml
- user_management/docker/docker-compose.yaml
- user_stats/docker/docker-compose.yaml
- Fix database health checks that produce log errors
- Reducing the number of max retries
> fix health check

- front/app/src/js/components/pages/tournaments/TournamentDetails.js
- front/app/src/js/components/pages/tournaments/Tournaments.js
Increment players counter when you join a tournament
> Increment players counter when you join a tournament

- matchmaking/src/settings.py
- pong_server/src/game_creator/game_creator/settings.py
- tournament/src/tournament/settings.py
- user_management/src/user_management/settings.py
- user_stats/src/user_stats/settings.py
...to prevent error 500 when POST requests lack a slash at the end 
BEFORE :
AFTER :
> APPEND_SLASH set to false 

- front/app/src/js/Theme.js
You can now listen for theme changes using Theme.event in a component like this:
```js
import {Theme} from '@js/Theme.js';
super.addComponentEventListener(document, Theme.event, () => {
const theme = Theme.get();
console.log('Theme changed to', theme);
});
```
> 245 create theme event listenner

- front/app/src/js/components/layouts/Friends.js
- front/app/src/js/components/notifications/Notification.js
- front/app/src/js/components/pages/tournaments/TournamentsContent.js
- front/app/src/js/components/pages/user_profile/UserProfileContent.js
- front/app/src/js/components/pages/user_profile/UserProfileMatchList.js
- front/app/src/js/utils/api/UserManagementClient.js
- front/app/src/js/utils/cache/UsersCache.js
- front/app/src/js/utils/cache/index.js
All user information, such as username and userId, which is intended to remain unchanged, is now cached.
> 246 add username cache

- front/app/src/js/components/buttons/GithubButton.js
- front/app/src/js/components/buttons/IntraButton.js
- front/app/src/js/components/layouts/FriendsSidebar.js
- front/app/src/js/components/navbar/NotificationNav.js
- front/app/src/js/components/notifications/Notification.js
- front/app/src/js/components/pages/home/Home.js
- front/app/src/js/components/pages/local/Local.js
- front/app/src/js/components/pages/multiplayer/Multiplayer.js
- front/app/src/js/components/pages/tournaments/TournamentsContent.js
- front/app/src/js/components/pages/user_profile/UserProfile.js
- front/app/src/js/utils/api/BaseClient.js
- front/app/src/js/utils/cache/Cache.js
- Handle network errors
- Check auth
> Fix crashes on the front

- user_management/doc/User_management.md
- user_management/src/user/tests.py
- user_management/src/user/urls.py
- user_management/src/user/views/avatar.py
Also, <str:username> parameter is not required anymore for `POST /user/avatar` et `DELETE /user/avatar`
> update avatar and verify email doc

- crontab/docker-compose.yaml
- docker-compose.yaml
- front/docker/docker-compose.yaml
- notification/docker/docker-compose.yaml
- pong_server/docker/docker-compose.yaml
- tournament/docker/docker-compose.yaml
- user_management/docker/docker-compose.yaml
- user_stats/docker/docker-compose.yaml
Compatibility with Docker Compose version v2.24.6
> move depends-on in global docker-compose

- Makefile
- common/src/generate_env.py
- docker-compose.yaml
- notification/docker/docker-compose.yaml
- notification/docker/postgres/Dockerfile
- notification/docker/postgres/check_health.sh
- notification/docker/postgres/healthcheck.sh
- tournament/docker/docker-compose.yaml
- tournament/docker/postgres/Dockerfile
- tournament/docker/postgres/check_health.sh
- tournament/docker/postgres/healthcheck.sh
- user_management/docker/docker-compose.yaml
- user_management/docker/postgres/Dockerfile
- user_management/docker/postgres/check_health.sh
- user_management/docker/postgres/healthcheck.sh
- user_stats/docker/docker-compose.yaml
- user_stats/docker/postgres/Dockerfile
- user_stats/docker/postgres/check_health.sh
- user_stats/docker/postgres/healthcheck.sh
All container launch errors corrected. Let me know if you still have errors, but normally this PR fixes everything.
> 375 fix docker compose

- front/app/src/js/components/pages/home/HomeContent.js
- front/app/src/js/components/pages/tournaments/TournamentsContent.js
- front/app/src/js/utils/api/PongServerClient.js
- front/app/src/js/utils/api/index.js
- pong_server/src/game_creator/api/urls.py
The added feature now enables the 'tournaments' and 'multiplayer' pages to automatically redirect to an ongoing game if one is active. This means that if a user logs in during a match or after a crash, they will be automatically redirected to their ongoing game, allowing them to seamlessly resume where they left off.
> 352 auto redirect player in game

- front/app/src/js/components/game/Engine/_GameSocketIO.js
- front/app/src/js/components/game/Engine/_ThreeJS.js
- front/app/src/js/components/game/Scene/Player/Player.js
- front/app/src/js/components/game/Scene/Player/_Board.js
- front/app/src/js/components/game/Scene/PlayerLocation.js
- front/app/src/js/components/game/Scene/Scene.js
- front/app/src/js/components/game/game.js
- pong_server/src/game_server/Game/GameManager.py
Add a card menu at the end of a game with the game result
> 378 implement game end page

- front/app/src/js/components/game/Engine/_KeyHookHandler.js
- front/app/src/js/components/game/Engine/_ThreeJS.js
- front/app/src/js/components/pages/home/HomeContent.js
The game can now be played on mobile by pressing on the left or right side of the screen in landscape mode, and on the bottom or top in portrait mode.
> 377 implement mobile game control

- user_management/src/user_management/settings.py
> USER_MANAGEMENT_IP is now correclty formatted (again)

- front/app/src/js/components/pages/settings/SettingsContent.js
By default, when you press enter, the first button of the form is triggered. This caused a deletion of the avatar
> add button type in settings form

- front/app/src/js/components/game/Engine/_GameSocketIO.js
- front/app/src/js/components/game/Scene/Ball.js
- front/app/src/js/components/game/Scene/CollisionHandler.js
- front/app/src/js/components/game/Scene/Match.js
- front/app/src/js/components/game/Scene/Scene.js
- front/app/src/js/components/game/ServerTime.js
- front/doc/pong.md
- pong_server/src/game_server/ClientManager.py
- pong_server/src/game_server/EventEmitter.py
- pong_server/src/game_server/EventHandler.py
- pong_server/src/game_server/Game/CollisionHandler.py
- pong_server/src/game_server/Game/GameManager.py
- pong_server/src/game_server/Server.py
The client now tries to account for latency by calculating the average latency it has with the server and updating the ball position as soon as it receives the update_ball_position event
> Client now tries to account for latency

- front/app/src/js/components/game/Scene/Player/_Board.js
- front/app/src/js/components/game/ServerTime.js
Fixed the goal position not updating correctly when a board needs to rotate for the next match
> Fixed tournaments

- front/app/src/js/components/game/Scene/Ball.js
- front/app/src/js/components/game/Scene/CollisionHandler.js
- front/app/src/js/components/game/Scene/Player/Paddle.js
- pong_server/src/game_server/Game/Ball.py
- pong_server/src/game_server/Game/CollisionHandler.py
- pong_server/src/game_server/Game/Player/Paddle.py
- pong_server/src/game_server/settings.py
Gameplay is now more similar to the original pong
> Gameplay overhaul

- front/app/src/js/components/game/Engine/Engine.js
- front/app/src/js/components/game/Engine/_ThreeJS.js
Frees the GPU-related resources allocated by ThreeJS scene and renderer.
> Clean up threeJS scene

- front/app/src/js/components/game/Engine/_GameSocketIO.js
- front/app/src/js/components/game/Scene/Match.js
- front/app/src/js/components/game/Scene/PaddleBoundingBox.js
- front/app/src/js/components/game/Scene/Player/Paddle.js
- front/app/src/js/components/game/Scene/Player/Player.js
- front/app/src/js/components/game/Scene/Player/_Board.js
- front/app/src/js/components/game/Scene/Scene.js
- front/doc/pong.md
- pong_server/src/game_server/AntiCheat.py
- pong_server/src/game_server/EventEmitter.py
- pong_server/src/game_server/EventHandler.py
- pong_server/src/game_server/Game/GameManager.py
- pong_server/src/game_server/Game/Match.py
- pong_server/src/game_server/Game/Player/Paddle.py
- pong_server/src/game_server/Game/Player/Player.py
- pong_server/src/game_server/settings.py
The board movements are now animated during tournaments
> Tournament animations

- user_management/src/user/views/delete_account.py
a 500 popped up whenever you tried to delete your account while having pending friend request
checking `if friend.status == Friend.ACCEPTED` before removing every friend while deleting account
> fix 500 removing every friend while deleting account
